name: "Create release or prerelease"
description: "This action creates a release if the working branch is main and a prerelease if it´s not main"

inputs:
  name:
    description: "Name of the Chart"
    required: true
  version:
    description: "Version of the Chart"
    required: true
  token:
    description: "Token to publish a new release"
    required: true

runs:
  using: composite
  steps: 

      - name: Print out inputs
        shell: bash
        run: echo 'Theses are my input. my name is ${{ inputs.name }}, my version is ${{ inputs.version }} and last my secrets ${{ inputs.token }} '

      - name: Get current date
        shell: bash
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Check if a new prerelease for chart should be created
        if: ${{ github.ref_name != 'main'}}
        uses: actions/checkout@v3

      - name: Create preRelease
        if: ${{ github.ref_name != 'main'}}
        id: create_Prerelease
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ inputs.token }}
        with:
          tag_name: ${{ inputs.name }}-v${{ inputs.version }}-prerelease-${{ github.ref_name }}-${{ steps.date.outputs.date }}
          release_name: ${{ inputs.name }}-v${{ inputs.version }}-prerelease-${{ github.ref_name }}
          body: |
            Be aware that this a prerelease. This version is not stable
          draft: false
          prerelease: true

      - name: Check if a new release for chart should be created
        if: ${{ github.ref_name == 'main'}}
        uses: actions/checkout@v3

      - name: Create release
        if: ${{ github.ref_name == 'main'}}
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ inputs.token }}
        with:
          tag_name: ${{ inputs.name }}-v${{ inputs.version }}-${{ github.ref_name }}
          release_name: ${{ inputs.name }}-v${{ inputs.version }}-${{ github.ref_name }}
          body: |
            This is a stable release
          draft: false
          prerelease: false

          


