name: "Create release or prerelease"
description: "This action creates a release if the working branch is main and a prerelease if it´s not main"

inputs:
  name:
    description: "Name of the Chart"
    required: true
  version:
    description: "Version of the Chart"
    required: true
  token:
    description: "Token to publish a new release"
    required: true

runs:
  using: composite
  steps: 
      - name: echo
        shell: bash
        run: echo ' Det her skal være meget meget meget meget langt ${{inputs.name}} laaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaangt'

  
      - name: Check if a new prerelease for chart should be created
        if: ${{ github.ref_name != 'main'}}
        uses: actions/checkout@v2

      - name: Create preRelease
        if: ${{ github.ref_name != 'main'}}
        id: create_Prerelease_${{ inputs.name }}
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ inputs.token }}
          name: ${{inputs.name}}
        with:
          tag_name: ${{ env.name }}-v${{ inputs.version }}-prerelease-${{ github.ref_name }}
          release_name: ${{ env.name }}-v${{ inputs.version }}-prerelease-${{ github.ref_name }}
          body: |
            Be aware that this a prerelease. This version is not stable
          draft: false
          prerelease: true

      - name: Check if a new release for chart should be created
        if: ${{ github.ref_name == 'main'}}
        uses: actions/checkout@v2

      - name: Create release
        if: ${{ github.ref_name == 'main'}}
        id: create_release_${{ inputs.name }}
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ inputs.token }}
          name: ${{ inputs.name }} 
        with:
          tag_name: ${{ env.name }}-v${{ inputs.version }}-prerelease-${{ github.ref_name }}
          release_name: ${{ env.name }}-v${{ inputs.version }}-prerelease-${{ github.ref_name }}
          body: |
            This is a stable release
          draft: false
          prerelease: false


