name: "Create release or prerelease"
description: "This action creates a release if the working branch is main and a prerelease if it´s not main"

inputs:
  name:
    description: "Name of the Chart"
    required: true
  version:
    description: "Version of the Chart"
    required: true
  token:
    description: "Token to publish a new release"
    required: true



runs:
  using: composite
  steps: 

      - name: Get current date
        shell: bash
        id: date
        run: echo "::set-output name=date::$(date +%s)"

      - name: Checkout
        uses: actions/checkout@v3

      - name: Collect template for release notes
        id: releaseTemplate
        uses: andstor/file-reader-action@v1
        with:
          path: ".github/ReleaseTemplate.txt"
          
      - name: print release note template
        run: echo "${{ steps.releaseTemplate.outputs.contents }}"
        shell: bash

      - name: Release
        if: ${{ github.ref_name == 'main'}}
        uses: softprops/action-gh-release@v1
        with:
          body_path: ${{ github.workspace }}\.github\ReleaseTemplate.txt
          token: ${{ inputs.token }}
          tag_name: ${{ inputs.name }}-v${{ inputs.version }}-${{ github.ref_name }}
          preRelease: false
          name: ${{ inputs.name }}-v${{ inputs.version }}-${{ github.ref_name }}

      - name: Pre-release
        if: ${{ github.ref_name != 'main'}}
        uses: softprops/action-gh-release@v1
        with:
          body_path: ${{ github.workspace }}\.github\ReleaseTemplate.txt
          token: ${{ inputs.token }}
          tag_name: ${{ inputs.name }}-v${{ inputs.version }}-prerelease-${{ github.ref_name }}-${{ steps.date.outputs.date }}
          preRelease: true
          name: ${{ inputs.name }}-v${{ inputs.version }}-prerelease-${{ github.ref_name }}
