---
# Source: cheetah-flink-native/templates/flink-deployment.yaml
apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  name: test-cheetah-flink-native
  annotations:
    vault.security.banzaicloud.io/vault-tls-secret: vault-tls
    vault.security.banzaicloud.io/vault-serviceaccount: default
spec:
  image: "ghcr.io/trifork/cheetah-example-processing:test-environment-patch"
  imagePullPolicy: Always
  serviceAccount: test-cheetah-flink-native
  flinkVersion: "v1_14"


  ingress:
    template: "flink.cheetah.trifork.dev/{{namespace}}/{{name}}(/|$)(.*)"
    className: "nginx"
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: "/$2"

  job:
    jarURI: local:///opt/flink/examples/streaming/StateMachineExample.jar
    parallelism: 2
    # entryClass: 
    state: running

    upgradeMode: "savepoint"

  flinkConfiguration:
    s3.path-style-access: "true"
    state.savepoints.dir: "s3p://flink/test-cheetah-flink-native/savepoints"
    state.checkpoints.dir: "s3p://flink/test-cheetah-flink-native/checkpoints"
    state.backend: "hashmap"
    high-availability: org.apache.flink.kubernetes.highavailability.KubernetesHaServicesFactory
    high-availability.storageDir: "s3p://flink/test-cheetah-flink-native/ha"
    metrics.reporter.prom.class: "org.apache.flink.metrics.prometheus.PrometheusReporter"
    metrics.reporter.prom.port: "9249"
    metrics.reporters: "prom"
    execution.checkpointing.interval: "10 minutes"
    execution.checkpointing.min-pause: "10 minutes"
    execution.checkpointing.timeout: "5 minutes"
    rest.flamegraph.enabled: "true"
    taskmanager.numberOfTaskSlots: "2"
    s3.access-key: "vault:secret/data/flink-teste/cheetah-flink-s3#accessKey"
    s3.secret-key: "vault:secret/data/flink-teste/cheetah-flink-s3#secretKey"
    s3.endpoint: "vault:secret/data/flink-teste/cheetah-flink-s3#endpoint"
  
  jobManager:
    replicas: 1
  
    resource:
      cpu: 0.5
      memory: 1Gb
  
    podTemplate:
      apiVersion: v1
      kind: Pod
      metadata:
        name: job-manager-pod-template
      spec:
        containers:
          - name: flink-main-container
            ports:
              - containerPort: 9249
                name: metrics
            env:
              - name: S3_ACCESS_KEY
                valueFrom:
                  secretKeyRef:
                    name: cheetah-flink-s3
                    key: accessKey
                    optional: false
              - name: S3_SECRET_KEY
                valueFrom:
                  secretKeyRef:
                    name: cheetah-flink-s3d
                    key: secretKey
                    optional: false
              - name: FLINK_S3_ENDPOINT
                value: http://minio.minio.svc.cluster.local:9000
            # automountServiceAccountToken: false
  
            volumeMounts:
              - name: s3-config
                mountPath: /opt/flink/conf/extra
  
        volumes:
          - name: s3-config
            secret:
              secretName: test-cheetah-flink-native-s3
              items:
                - key: test.yaml
                  path: test.yaml

  
  taskManager:
  
    resource:
      cpu: 0.5
      memory: 1Gb
  
    podTemplate:
      apiVersion: v1
      kind: Pod
      metadata:
        name: task-manager-pod-template
      spec:
        containers:
          - name: flink-main-container
            ports:
              - containerPort: 9249
                name: metrics
                protocol: TCP
            env:
              - name: AWS_ACCESS_KEY
                valueFrom:
                  secretKeyRef:
                    name: cheetah-flink-s3
                    key: accessKey
                    optional: false
              - name: AWS_SECRET_KEY
                valueFrom:
                  secretKeyRef:
                    name: cheetah-flink-s3
                    key: secretKey
                    optional: false
              - name: FLINK_S3_ENDPOINT
                value: http://minio.minio.svc.cluster.local:9000
            # automountServiceAccountToken: false
