target-branch: main
remote: origin
chart-dirs:
  - charts
check-version-increment: false
debug: true
validate-chart-schema: true
validate-maintainers: false
validate-yaml: true
lint-conf: lintconf.yaml
