checks:
  # reliability
  deploymentMissingReplicas: warning
  livenessProbeMissing: warning
  metadataAndNameMismatched: ignore
  missingPodDisruptionBudget: ignore
  pdbDisruptionsIsZero: warning
  priorityClassNotSet: ignore
  pullPolicyNotAlways: ignore
  readinessProbeMissing: warning
  tagNotSpecified: ignore # shouldn't be specified in a generic chart

  # efficiency
  cpuLimitsMissing: warning
  cpuRequestsMissing: warning
  memoryLimitsMissing: warning
  memoryRequestsMissing: warning

  # security
  automountServiceAccountToken: ignore
  clusterrolePodExecAttach: danger
  clusterrolebindingClusterAdmin: danger
  clusterrolebindingPodExecAttach: danger
  dangerousCapabilities: danger
  hostIPCSet: danger
  hostNetworkSet: danger
  hostPIDSet: danger
  hostPortSet: warning
  insecureCapabilities: warning
  linuxHardening: danger
  missingNetworkPolicy: ignore
  notReadOnlyRootFilesystem: warning
  privilegeEscalationAllowed: danger
  rolePodExecAttach: danger
  rolebindingClusterAdminClusterRole: ignore # TODO: change to danger
  rolebindingClusterAdminRole: danger
  rolebindingClusterRolePodExecAttach: ignore # TODO: change to danger
  rolebindingRolePodExecAttach: danger
  runAsPrivileged: danger
  runAsRootAllowed: danger
  sensitiveConfigmapContent: danger
  sensitiveContainerEnvVar: danger
  tlsSettingsMissing: warning
