- cheetah-application:
    items:
      - name: v0.9.0
        href: charts/cheetah-application/v0.9.0/README.md
      - name: v0.8.0
        href: charts/cheetah-application/v0.8.0/README.md
- flink-job:
  items:
- image-automation:
  items:
- opensearchrole:
  items:
- redpanda-console-oauth2proxy:
  items:
