- name: cheetah-application
  items:
    - name: v0.8
      href: cheetah-application/v0.8/README.md
- name: flink-job
  items:
- name: image-automation
  items:
- name: opensearchrole
  items:
    - name: v0.3
      href: opensearchrole/v0.3/README.md
- name: redpanda-console-oauth2proxy
  items:
