- name: Overview
  href: README.md
- name: cheetah-application
  items:
    - name: v0.10
      href: cheetah-application/v0.10/README.md
    - name: v0.9
      href: cheetah-application/v0.9/README.md
    - name: v0.8
      href: cheetah-application/v0.8/README.md
- name: flink-job
  items:
    - name: v2.1
      href: flink-job/v2.1/README.md
- name: image-automation
  items:
    - name: v0.2
      href: image-automation/v0.2/README.md
- name: opensearchrole
  items:
    - name: v0.3
      href: opensearchrole/v0.3/README.md
- name: redpanda-console-oauth2proxy
  items:
    - name: v3.1
      href: redpanda-console-oauth2proxy/v3.1/README.md
    - name: v1.4
      href: redpanda-console-oauth2proxy/v1.4/README.md
    - name: v1.3
      href: redpanda-console-oauth2proxy/v1.3/README.md
    - name: v1.2
      href: redpanda-console-oauth2proxy/v1.2/README.md
    - name: v1.1
      href: redpanda-console-oauth2proxy/v1.1/README.md
