name: "Check if chart release exist"
description: "Uses check"

inputs:
  name:
    description: "Name of the Chart"
    required: true

runs:
  using: composite
  steps:
    - name: Print branch
      shell: bash
      run: echo 'This is the working branch ${{github.ref_name}}'

    - name: Read Chart.yaml and collect version
      id: version
      uses: jbutcher5/read-yaml@1.6
      with:
        file: "charts/${{inputs.name}}/Chart.yaml" # File to read from
        key-path: '["version"]' # Access the runs key then the using key and returns the value.

    - name: print cheetah-application-version if new
      run: echo "This is the latest version ${{ steps.version.outputs.data }}"

    - name: Setup python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install python dependencies
      run: pip install pyyaml requests

    - name: run script
      id: python
      run: |
        output=$(python .github/scripts/test2.py --token ${{ secrets.GITHUB_TOKEN }} --branch ${{ github.ref_name }} --chartName ${{inputs.name}} --version ${{ steps.version.outputs.data }} )
        out2="${output//'%'/'%25'}"
        echo "::set-output name=changelog2::$out2"


    - name: print variable from python
      run: |
          echo "${{ steps.python.outputs.changelog2 }}, release or prerelease already exist for ${{inputs.name}}"

    - name: Create a preRelease or release if one does not exist
      if: ${{ steps.python.outputs.changelog2 == 'false'}}
      uses: ./.github/actions/create-release-or-prerelease
      with:
        name: ${{inputs.name}}
        version: ${{ steps.version.outputs.data }}


