name: "Check if chart release exist"
description: "This action checks if a specific release exist, if not it starts an other action that creates a new release"

inputs:
  name:
    description: "Name of the Chart"
    required: true

  token:
    description: "Token to access github API"
    required: true

  branch:
    description: "The working branch"
    required: true

  repo:
    description: The repository to fetch releases from
    required: true

runs:
  using: composite
  steps:
    - name: Print branch
      run: echo 'Working branch ${{ inputs.branch }}'
      shell: bash

    - name: print repo
      run: echo ${{inputs.repo}}
      shell: bash

    - name: Read Chart.yaml and collect version
      id: version
      uses: jbutcher5/read-yaml@1.6
      with:
        file: "charts/${{inputs.name}}/Chart.yaml" # File to read from
        key-path: '["version"]' # Access the runs key then the using key and returns the value.

    - name: print cheetah-application-version if new
      run: echo "This is the latest version ${{ steps.version.outputs.data }}"
      shell: bash

    - name: Check if a release exist
      
      id: release
      env:
        GH_TOKEN: ${{ inputs.token }} 
      if: ${{ github.ref_name == 'main' }}
      run: |
        gh release view ${{ inputs.name }}-v${{ steps.version.outputs.data }}-${{ github.ref_name }} --json isPrerelease --jq '.isPrerelease')
      shell: bash
      continue-on-error: true

    - name: Check if a preRelease exist
      id: preRelease
      env:
        GH_TOKEN: ${{ inputs.token }} 
      if: ${{ github.ref_name }} != 'main'
      run: |
        gh release view ${{ inputs.name }}-v${{ inputs.version }}-prerelease-${{ github.ref_name }} --json isPrerelease --jq '.isPrerelease')
      shell: bash
      continue-on-error: true

    - name: Delete old preRelease
      if: steps.preRelease.outcome == 'success'
      run: gh release delete ${{ inputs.name }}-v${{ inputs.version }}-prerelease-${{ github.ref_name }}
      shell: bash

    - name: Create prerelease or release  
      if: steps.release.outcome == 'success' || steps.preRelease.outcome == 'success'
      uses: ./.github/actions/create-release-or-prerelease
      with:
        name: ${{ inputs.name }}
        version: ${{ steps.version.outputs.data }}
        token: ${{ inputs.token }}

    - name: print error message 
      if: steps.release.outcome != 'success' || steps.preRelease.outcome != 'success'
      run: echo "No release to fetch"
      shell: bash