# example values from docs.cheetah.trifork.dev/
image:
  repository: some-registry/some-image
  tag: v1.2.3
resources:
  requests:
    memory: 1Mi
    cpu: 10m
  limits:
    memory: 12Mi
    cpu: 100m
ingress:
  enabled: true
  hosts:
    - host: prod.cheetah.trifork.dev
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    secretName: tls-secret
monitoring:
  enabled: true
pdb:
  create: true
  minAvailable: 1
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80
