image:
  repository: ghcr.io/trifork/cheetah-webapi
  tag: main-2058545582 # {"$imagepolicy": "query-trifork-team:webapi-automation:tag"}
imagePullSecrets:
  - name: accesstoken-ghcr-io
podAnnotations:
  linkerd.io/inject: disabled
podLabels:
  mynameis: georgio
resources:
  requests:
    memory: "64Mi"
    cpu: "250m"
  limits:
    memory: "128Mi"
    cpu: "500m"
ingress:
  enabled: true
  hosts:
    - host: webapi.cheetah.trifork.dev
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    secretName: tls-secret
env:
  - name: DOTNET_ENVIRONMENT
    value: "Development"
  - name: ElasticSearch__DefaultIndex
    value: "test_watermeterreading_customera_2020"
  - name: ElasticSearch__IndexNamePrefix
    value: "test_watermeterreading"
  - name: ElasticSearch__Url
    value: "http://elasticsearch-coordinating-only.elasticsearch:9200"
    #tmp untill secret works
#- name: ElasticSearch__UserName
#  value: "elastic"
#- name: ElasticSearch__Password
#  value: "d6MR9LN8kwpqlZClVuP3WYxfZiuOEOEN"
envFrom:
  - secretRef:
      name: cheetah-webapi-secrets
startupProbe:
  enabled: false
livenessProbe:
  enabled: false
readinessProbe:
  enabled: false

monitoring:
  enabled: true
  port: 1854
  path: /metrics

volumes:
  - name: webapi-volume
    persistentVolumeClaim:
      claimName: webapi-files

volumeMounts:
  - name: webapi-volume
    mountPath: /files/