image:
  repository: ghcr.io/trifork/cheetah-webapi
  tag: main
imagePullSecrets:
  - name: accesstoken-ghcr-io

replicaCount: 2

podAnnotations:
  linkerd.io/inject: disabled
podLabels:
  mynameis: georgio

resources:
  requests:
    memory: "64Mi"
    cpu: "250m"
  limits:
    memory: "128Mi"
    cpu: "500m"

ingress:
  enabled: true
  hosts:
    - host: webapi.cheetah.trifork.dev
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    secretName: tls-secret

env:
  - name: DOTNET_ENVIRONMENT
    value: "Development"
  - name: ElasticSearch__DefaultIndex
    value: "test_watermeterreading_customera_2020"
  - name: ElasticSearch__IndexNamePrefix
    value: "test_watermeterreading"
  - name: ElasticSearch__Url
    value: "http://elasticsearch-coordinating-only.elasticsearch:9200"

envFrom:
  - secretRef:
      name: cheetah-webapi-secrets

podSecurityContext:
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault
securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop:
      - ALL

monitoring:
  enabled: true
  port: 1854
  path: /metrics

volumes:
  - name: webapi-volume
    persistentVolumeClaim:
      claimName: webapi-files

volumeMounts:
  - name: webapi-volume
    mountPath: /files/

pdb:
  create: true
