image:
  repository: flink
  tag: 1.16

imagePullSecrets:
  - name: pullsecret

ingress:
  enabled: true
  certType: staging

monitoring:
  enabled: true

podTemplate:
  spec:
    containers:
      - name: sleepybox
        securityContext:
          allowPrivilegeEscalation: false
          runAsGroup: 1001
          runAsUser: 1001
          capabilities:
            drop:
              - ALL
        image: bitnami/bitnami-shell:latest
        command:
          - /bin/sh
          - -c
          - while sleep 2; do echo "zzz"; done

flink:
  savepoints:
    enabled: true

  checkpoints:
    enabled: true

  job:
    jarURI: local:///opt/flink/examples/streaming/StateMachineExample.jar
    args: []
  flinkProperties:
    taskmanager.numberOfTaskSlots: 2
