# example values from docs.cheetah.trifork.dev/
image:
  repository: flink
  tag: 1.16
ingress:
  enabled: true
  domain: flink.cheetah.trifork.dev
  certType: prod
flink:
  version: v1_16
  jobManager:
    replicas: 2
    metrics:
      enabled: true
    resource:
      memory: 1Gb
      cpu: 0.1
  taskManager:
    replicas: 2
    metrics:
      enabled: true
    resource:
      memory: 1Gb
      cpu: 0.1
  job:
    jarURI: local:///opt/flink/examples/streaming/StateMachineExample.jar
    className: org.apache.flink.streaming.examples.statemachine.StateMachineExample
    parallelism: 2
monitoring:
  enabled: true
