image:
  repository: ghcr.io/trifork/cheetah-processing-example
  sha: "4a3db816d7e61d2f2ee709429abad01266450befb8aa230d4a2b1b1106e6f9bf"

imagePullSecrets:
  - name: pullsecret

ingress:
  enabled: true
  certType: staging

monitoring:
  enabled: true

flink:
  savepoints:
    enabled: true

  checkpoints:
    enabled: true

  job:
    jarFile: /opt/flink/usrlib/artifacts/processing-1.0-SNAPSHOT.jar
    className: com.trifork.cheetah.processing.ExampleJob
    name: ExampleJob
    args:
      - ---input-kafka-topic
      - processed
      - ---input-kafka-bootstrap-servers
      - kafka-brokers.kafka:9092
      - ---input-kafka-group.id
      - storage-1
      - ---es-hosts
      - elasticsearch-coordinating-only.elasticsearch:9200
      - ---es-user
      - elastic
      - ---es-password
      - d6MR9LN8kwpqlZClVuP3WYxfZiuOEOEN
      - ---es-index-prefix
      - test-2
  flinkProperties:
    taskmanager.numberOfTaskSlots: 2
    # scheduler-mode: reactive  # Currently not working
    rest.flamegraph.enabled: true
    execution.checkpointing.interval: 20 seconds
    execution.checkpointing.min-pause: 10 seconds
