image:
  repository: flink
  tag: 1.16

imagePullSecrets:
  - name: pullsecret

ingress:
  enabled: true
  certType: staging

monitoring:
  enabled: true

podTemplate:
  spec:
    containers:
      - name: flink-main-container
        env:
          - name: FOO
            value: BAR
        securityContext:
          allowPrivilegeEscalation: true
      - name: test-container
        securityContext:
          runAsGroup: 5050

securityContext:
  allowPrivilegeEscalation: false
  runAsUser: 9999
  runAsGroup: 9999
  capabilities:
    drop:
      - ALL

podSecurityContext:
  runAsNonRoot: true
  fsGroup: 9999
  seccompProfile:
    type: RuntimeDefault

flink:
  savepoints:
    enabled: true

  checkpoints:
    enabled: true

  job:
    jarURI: local:///opt/flink/downloads/flink-examples-streaming.jar
    className: org.apache.flink.streaming.examples.statemachine.StateMachineExample
    args: []
  flinkProperties:
    taskmanager.numberOfTaskSlots: 2
