fullnameOverride: flink-test

image:
  repository: flink
  pullPolicy: Always
  sha: f86e49fe98ed41ecae004470a0e35c83849cc8e2c0ad558e3ff702650ccdae46 # 1.16

imagePullSecrets:
  - name: pullsecret

restartNonce: 1

serviceAccount:
  name: flink-test

rbac:
  additionalRules:
    - apiGroups:
        - ""
      resources:
        - secrets
      verbs:
        - list

ingress:
  enabled: true
  domain: flink-test.cheetah.trifork.dev
  certType: prod

podTemplate:
  spec:
    containers:
      - name: sleepybox
        securityContext:
          allowPrivilegeEscalation: false
          runAsGroup: 1001
          runAsUser: 1001
          capabilities:
            drop:
              - ALL
        image: bitnami/bitnami-shell:latest
        command:
          - /bin/sh
          - -c
          - while sleep 2; do echo "zzz"; done

podSecurityContext:
  seccompProfile:
    type: Default

securityContext:
  readOnlyRootFilesystem: true

flink:
  version: v1_16

  configuration:
    taskmanager.numberOfTaskSlots: "2"
    kubernetes.taskmanager.cpu.limit-factor: "10.0"
    kubernetes.jobmanager.cpu.limit-factor: "10.0"

  jobManager:
    replicas: 2

    metrics:
      enabled: true

    resource:
      memory: 1Gb
      cpu: 0.1

  taskManager:
    replicas: 2

    metrics:
      enabled: true

    resource:
      memory: 1Gb
      cpu: 0.1

  job:
    jarURI: local:///opt/flink/examples/streaming/StateMachineExample.jar
    className: org.apache.flink.streaming.examples.statemachine.StateMachineExample
    args: []

    upgradeMode: "stateless"

    parallelism: 2

monitoring:
  enabled: true
  podTargetLabels:
    - component
    - cluster

  flinkProperties:
    metrics.reporters: prom
    metrics.reporter.prom.port: "9249"
