image:
  repository: ghcr.io/trifork/cheetah-example-processing
  tag: main

imagePullSecrets:
  - name: pullsecret-ghcr-io

ingress:
  enabled: false
  certType: staging

monitoring:
  enabled: true

flink:
  savepoints:
    enabled: true

  checkpoints:
    enabled: true

  version: v1_14

  jobManager:
    additionalConfigs:
      automountServiceAccountToken: false

  taskManager:
    additionalConfigs:
      automountServiceAccountToken: false

  job:
    # upgradeMode: stateless
    jarURI: /opt/flink/examples/streaming/StateMachineExample.jar
    parallelism: 2
    args:
  flinkProperties:
    taskmanager.numberOfTaskSlots: 2
