{{- if .Values.internalSsl.enabled -}}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ printf "%s-mtls-issuer" ( include "flink-job.name" . ) | quote }}
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: {{ printf "%s-mtls-crt" ( include "flink-job.name" . ) | quote }}
spec:
  secretName: {{ printf "%s-mtls-secret" ( include "flink-job.name" . ) | quote }}
  issuerRef:
    name: {{ printf "%s-mtls-issuer" ( include "flink-job.name" . ) | quote }}
  keystores:
    jks:
      create: true
      passwordSecretRef: # Password used to encrypt the keystore
        key: password
        name: {{ printf "%s-mtls-password" ( include "flink-job.name" . ) | quote }}
{{- end -}}