---
apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  name: {{ include "flink-job.flinkDeploymentName" . }}
  labels:
    {{- include "flink-job.labels" . | nindent 4 }}
spec:
  image: {{ include "flink-job.image" . | quote }}
  imagePullPolicy: {{ .Values.image.pullPolicy }}
  serviceAccount: {{ include "flink-job.serviceAccountName" . }}
  flinkVersion: {{ .Values.version | quote }}
  {{- with .Values.restartNonce }}
  restartNonce: {{ . }}
  {{- end }}
  {{- with .Values.logConfiguration }}
  logConfiguration:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.mode }}
  mode: {{ . }}
  {{- end }}

  flinkConfiguration:
    security.ssl.internal.enabled: "true"
    security.ssl.internal.keystore: /flinkkeystore/internal.keystore
    security.ssl.internal.truststore: /flinkkeystore/internal.keystore
    security.ssl.internal.keystore-password: internal_store_password
    security.ssl.internal.truststore-password: internal_store_password
    security.ssl.internal.key-password: internal_store_password
    {{- include "flink-job.calculateConfigurations" . | nindent 4 -}}
 
  podTemplate:
  {{- with .Values.podTemplate }}
    {{- tpl . $ | nindent 4 -}}
  {{- end }}
    initContainers:
    - name: cert-creator
      image: docker.io/bitnami/java:11.0.20-8
      command: ["/bin/sh", "-c"]
      args:
        [
          "keytool -genkeypair -alias flink.internal -keystore /flinkkeystore/internal.keystore -dname \"CN=flink.internal\" -storepass internal_store_password -keyalg RSA -keysize 4096 -storetype PKCS12",
        ]
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          add: []
          drop:
            - ALL
        runAsGroup: 9999
        runAsUser: 9999
      volumeMounts:
        - mountPath: /flinkkeystore
          name: truststore
          readOnly: false    
  job:
    jarURI: {{ .Values.job.jarURI | quote }}
    {{- with .Values.job.entryClass }}
    entryClass: {{ . | quote }}
    {{- end }}
    {{- if or .Values.job.args .Values.job.topics }}
    args:
      {{- range .Values.job.topics }}
      {{- if .arg }}
      - {{ printf "--%s" (trimPrefix "--" .arg) | quote }}
      - {{ printf "%s" .name | quote }}
      {{- end }}
      {{- end }}
      {{- range .Values.job.args }}
      - {{ . | quote }}
      {{- end }}
    {{- end }}
    parallelism: {{ int .Values.job.parallelism }}
    state: {{ .Values.job.state }}
    {{- with .Values.job.savepointTriggerNonce }}
    savepointTriggerNonce: {{ . }}
    {{- end }}
    {{- with .Values.job.initialSavepointPath }}
    initialSavepointPath: {{ . }}
    {{- end }}
    {{- with .Values.job.allowNonRestoredState }}
    allowNonRestoredState: {{ . }}
    {{- end }}
    upgradeMode: {{ .Values.job.upgradeMode | quote }}

  jobManager:
    replicas: {{ int .Values.jobManager.replicas }}
    resource:
      {{- toYaml .Values.jobManager.resource | nindent 6 }}
    {{- with .Values.jobManager.podTemplate }}
    podTemplate:
      {{- tpl . $ | nindent 6 -}}
    {{- end }}

  taskManager:
    replicas: {{ int .Values.taskManager.replicas }}
    resource:
      {{- toYaml .Values.taskManager.resource | nindent 6 }}
    {{- with .Values.taskManager.podTemplate }}
    podTemplate:
      {{- tpl . $ | nindent 6 -}}
    {{- end }}
