{{- if and .Values.metrics.enabled .Values.metrics.podMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "flink-job.fullname" . }}
  labels:
    {{- include "flink-job.labels" . | nindent 4 }}
    {{- with .Values.metrics.podMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  podMetricsEndpoints:
    - port: metrics
      {{- with .Values.metrics.podMonitor.path }}
      path: {{ . }}
      {{- end }}
      {{- with .Values.metrics.podMonitor.interval }}
      interval: {{ . }}
      {{- end }}
      {{- with .Values.metrics.podMonitor.scrapeTimeout }}
      scrapeTimeout: {{ . }}
      {{- end }}
      {{- with .Values.metrics.podMonitor.metricRelabelings }}
      metricRelabelings:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.metrics.podMonitor.relabelings }}
      relabelings:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.metrics.podMonitor.extraMetricsEndpoints }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  podTargetLabels:
    {{- toYaml .Values.metrics.podMonitor.targetLabels | nindent 4 }}
  selector:
    matchLabels:
      app.kubernetes.io/component: metrics
      {{- include "flink-job.selectorLabels" . | nindent 6 }}
      {{- with .Values.metrics.podMonitor.selectors }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
{{- end -}}
