{{- if .Values.ingress.selfSigned -}}
{{- $ca := genCA "flink-job-ca" 365 -}}
{{- $cert := genSignedCert .Values.ingress.hostname nil (list .Values.ingress.hostname) 365 $ca -}}
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: {{ printf "%s-tls" .Values.ingress.hostname | quote }}
  labels:
    {{- include "flink-job.labels" . | nindent 4 }}
data:
  tls.crt: {{ $cert.Cert | b64enc }}
  tls.key: {{ $cert.Key | b64enc }}
  ca.crt: {{ $ca.Cert | b64enc }}
{{- end }}

{{- if .Values.internalSsl.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-mtls-password" ( include "flink-job.fullname" . ) | quote }}
stringData:
  password: {{ sha1sum (nospace (toString .Values.image)) | trunc 10 }}
{{- end -}}