{{- if and .Values.metrics.enabled .Values.metrics.serviceMonitor.enabled -}}
{{- with .Values.metrics.serviceMonitor -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "flink-job.fullname" $ }}
  labels:
    {{- include "flink-job.labels" $ | nindent 4 }}
    {{- with .labels }}
    {{- toYaml . | nindent 4 }}
    {{- end}}
spec:
  endpoints:
    - port: metrics
      {{- with .scheme }}
      scheme: {{ . }}
      {{- end }}
      {{- if eq .scheme "https" }}
      {{- with .tlsConfig }}
      tlsConfig:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}
      {{- with .path }}
      path: {{ . }}
      {{- end }}
      {{- with .interval }}
      interval: {{ . }}
      {{- end }}
      {{- with .scrapeTimeout }}
      scrapeTimeout: {{ . }}
      {{- end }}
      {{- with .relabelings }}
      relabelings:
        {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- with .metricsRelabelings }}
      metricsRelabelings:
        {{- toYaml . | nindent 6 }}
      {{- end }}    
    {{- with .extraMetricsEndpoints }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  podTargetLabels:
    {{- toYaml .targetLabels | nindent 4 }}
  selector:
    matchLabels:
      app.kubernetes.io/component: metrics
      {{- include "flink-job.selectorLabels" $ | nindent 6 }}
      {{- with .selectors }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
{{- end -}}
{{- end -}}
