{{- if and .Values.metrics.enabled .Values.metrics.service.enabled -}}
{{- $port := .Values.metrics.port -}}
{{- with .Values.metrics.service -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "flink-job.fullname" $ }}-metrics
  labels:
    app.kubernetes.io/component: metrics
    {{- include "flink-job.labels" $ | nindent 4 }}
    {{- with .labels }}
    {{- toYaml . | nindent 4 }}
    {{- end}}
spec:
  ports:
    - name: metrics
      port: {{ $port }}
      protocol: TCP
      targetPort: {{ .targetPort }}
  type: ClusterIP
  selector:
    {{- include "flink-job.selectorLabels" $ | nindent 4 }}
    {{- with .selectors }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end -}}
{{- end -}}
