# helm template opensearchrole charts/flink-job -f charts/flink-job/ci/minimal-values.yaml > output.yaml
image:
  repository: flink
  tag: 1.16

job:
  jarURI: local:///opt/flink/examples/streaming/StateMachineExample.jar

storage:
  scheme: s3
  baseDir: /flink-data
