---
# Source: cheetah-flink/templates/flinkjobcluster.yaml
apiVersion: flinkoperator.k8s.io/v1beta1
kind: FlinkCluster
metadata:
  name: tmp-flink-cheetah-flink
  labels:
    helm.sh/chart: cheetah-flink-0.1.14
    app.kubernetes.io/name: cheetah-flink
    app.kubernetes.io/instance: tmp-flink
    app.kubernetes.io/version: "0.0.1"
    app.kubernetes.io/managed-by: Helm
spec:
  flinkVersion: "1.14.4"
  image:
    name: "flink:main"
  jobManager:
    accessScope: Cluster
    ports:
      ui: 8081
    extraPorts:
      - containerPort: 9249
        name: metrics
    resources:
      limits:
        cpu: "5"
        memory: 1Gi
      requests:
        cpu: 100m
        memory: 256Mi
  taskManager:
    replicas: 1
    extraPorts:
      - containerPort: 9249
        name: metrics
        protocol: TCP
    resources:
      limits:
        cpu: "5"
        memory: 2Gi
      requests:
        cpu: 100m
        memory: 512Mi
  job:
    jarFile: ""
    className: ""
    parallelism: 2
    restartPolicy: Never
    savepointsDir: "s3p://flink/tmp-flink-cheetah-flink/savepoints"
    podAnnotations:
      linkerd.io/inject: disabled

  flinkProperties:
    s3.access-key: "flink-s3"
    s3.secret-key: "Z00PBmpZ2aHXlyjVqAigvK9K8YJgs8KT"
    s3.endpoint: "http://minio.minio.svc.cluster.local:9000"
    s3.path-style-access: "true"
    state.savepoints.dir: "s3p://flink/tmp-flink-cheetah-flink/savepoints"
    state.checkpoints.dir: "s3p://flink/tmp-flink-cheetah-flink/checkpoints"
    state.backend: hashmap
    execution.checkpointing.interval: "10 minutes"
    execution.checkpointing.min-pause: "10 minutes"
    execution.checkpointing.timeout: "5 minutes"
    rest.flamegraph.enabled: "true"
    taskmanager.numberOfTaskSlots: "1"
