apiVersion: v1
kind: Pod
metadata:
  labels:
    app: test-cheetah-flink-native
    component: jobmanager
    pod-template-hash: 97744457b
    type: flink-native-kubernetes
  name: test-cheetah-flink-native-tmp
  namespace: flink-teste
spec:
  initContainers:
  - name: move-config
    image: busybox
    command: ['sh', '-c', 'cp /flink-conf/* /tmp/config']
    volumeMounts:
      - name: tmp-vol
        mountPath: /tmp/config
      - name: flink-config-volume
        mountPath: /flink-conf
  containers:
  - args:
    - bash
    - -c
    - kubernetes-jobmanager.sh kubernetes-application
    command:
    - /docker-entrypoint.sh
    env:
    - name: S3_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          key: accessKey
          name: cheetah-flink-s3
          optional: false
    - name: S3_SECRET_KEY
      valueFrom:
        secretKeyRef:
          key: secretKey
          name: cheetah-flink-s3
          optional: false
    - name: FLINK_S3_ENDPOINT
      value: http://minio.minio.svc.cluster.local:9000
    - name: _POD_IP_ADDRESS
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: status.podIP
    image: ghcr.io/trifork/cheetah-example-processing:test-environment-patch
    imagePullPolicy: Always
    name: flink-main-container
    ports:
    - containerPort: 9249
      name: metrics
      protocol: TCP
    - containerPort: 8081
      name: rest
      protocol: TCP
    - containerPort: 6123
      name: jobmanager-rpc
      protocol: TCP
    - containerPort: 6124
      name: blobserver
      protocol: TCP
    resources:
      limits:
        cpu: 500m
        memory: 1Gi
      requests:
        cpu: 500m
        memory: 1Gi
    volumeMounts:
    - mountPath: /opt/flink/conf/extra
      name: s3-config
    - mountPath: /opt/flink/conf
      name: tmp-vol
    - mountPath: /opt/flink/pod-template
      name: pod-template-volume
  imagePullSecrets:
  - name: pullsecret-ghcr-io
  restartPolicy: Always
  serviceAccount: test-cheetah-flink-native
  serviceAccountName: test-cheetah-flink-native
  volumes:
  - name: tmp-vol
    emptyDir: {}
  - name: s3-config
    secret:
      defaultMode: 420
      items:
      - key: test.yaml
        path: test.yaml
      secretName: test-cheetah-flink-native-s3
  - configMap:
      defaultMode: 420
      items:
      - key: log4j-console.properties
        path: log4j-console.properties
      - key: flink-conf.yaml
        path: flink-conf.yaml
      name: flink-config-test-cheetah-flink-native
    name: flink-config-volume
  - configMap:
      defaultMode: 420
      items:
      - key: taskmanager-pod-template.yaml
        path: taskmanager-pod-template.yaml
      name: pod-template-test-cheetah-flink-native
    name: pod-template-volume
