apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvL3RyaWZvcmsiOnsiYXV0aCI6IlkyaGxaWFJoYUdKdmREcG5hSEJmVUdGNFJGWm5TbGRyTWtOc1lsWmtWMWRRYldKbFRtNU9WV2hoT0hGNk1IQlVNemxZIn19fQ==
kind: Secret
metadata:
  name: pullsecret-ghcr-io
  namespace: flink-test
type: kubernetes.io/dockerconfigjson
