apiVersion: flinkoperator.k8s.io/v1beta1
kind: FlinkCluster
metadata:
  name: {{ template "cheetah-flink.fullname" . }}
  labels:
    {{- include "cheetah-flink.labels" . | nindent 4 }}
spec:
  flinkVersion: {{ .Values.flink.version | quote }}
  image:
    name: {{ include "cheetah-flink.image" . | quote }}
    {{- with coalesce .Values.global.imagePullSecrets .Values.imagePullSecrets }}
    pullSecrets:
      {{- toYaml . | nindent 6 }}
    {{- end }}
  {{- with .Values.flink.envVars }}
  envVars:
    {{- toYaml . | nindent 4 }}
  {{- end }}

  jobManager:
    accessScope: {{ .Values.flink.jobManager.accessScope }}
    ports:
      ui: {{ .Values.flink.jobManager.ports.ui }}
    {{- with .Values.flink.jobManager.volumes }}
    volumes:
      {{- toYaml . | nindent 6}}
    {{- end }}
    {{- with .Values.flink.jobManager.volumeMounts }}
    volumeMounts:
      {{- toYaml . | nindent 6}}
    {{- end }}
    {{- if .Values.flink.jobManager.metrics.enabled }}
    extraPorts:
      {{- toYaml .Values.flink.jobManager.metrics.extraPorts | nindent 6 }}
    {{- end }}
    resources:
      {{- toYaml .Values.flink.jobManager.resources | nindent 6 }}
    podLabels:
      {{- include "cheetah-flink.backstageLabels" . | nindent 6 }}
      {{- range $key, $val := .Values.flink.jobManager.podLabels }}
      {{ $key }}: {{ $val | quote }}
      {{- end }}
    {{- with .Values.flink.jobManager.podAnnotations }}
    podAnnotations:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.flink.jobManager.additionalConfigs }}
      {{- toYaml . | nindent 4 }}
    {{- end }}

  taskManager:
    replicas: {{ with .Values.flink.taskManager.replicas }}
    {{- with .Values.flink.taskManager.volumes }}
    volumes:
      {{- toYaml . | nindent 6}}
    {{- end }}
    {{- with .Values.flink.taskManager.volumeMounts }}
    volumeMounts:
      {{- toYaml . | nindent 6}}
    {{- end }}
    {{- if .Values.flink.taskManager.metrics.enabled }}
    extraPorts:
      {{- toYaml .Values.flink.taskManager.metrics.extraPorts | nindent 6 }}
    {{- end }}
    resources:
      {{- toYaml .Values.flink.taskManager.resources | nindent 6 }}
    podLabels:
      {{- include "cheetah-flink.backstageLabels" . | nindent 6 }}
      {{- range $key, $val := .Values.flink.taskManager.podLabels }}
      {{ $key }}: {{ $val | quote }}
      {{- end }}
    {{- with .Values.flink.taskManager.podAnnotations }}
    podAnnotations:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.flink.taskManager.additionalConfigs }}
      {{- toYaml . | nindent 4 }}
    {{- end }}


  {{- with .Values.flink.job }}
  job:
    jarFile: {{ .jarFile | quote }}
    className: {{ .className | quote }}
    {{- with .args }}
    args:
      {{- range . }}
      - {{ . | quote }}
      {{- end -}}
    {{- end }}
    parallelism: {{ .parallelism }}
    restartPolicy: {{ .restartPolicy }}
    {{- if $.Values.flink.savepoints.enabled }}
    savepointsDir: "{{ include "cheetah-flink.storageDir" $ }}/savepoints"
    {{- end }}
    {{- with .volumes }}
    volumes:
      {{ toYaml . | nindent 6}}
    {{- end }}
    {{- with .volumeMounts }}
    volumeMounts:
      {{ toYaml . | nindent 6}}
    {{- end }}
    {{- with .podLabels }}
    podLabels:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .podAnnotations }}
    podAnnotations:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .additionalConfigs }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}

  flinkProperties:
  {{- if .Values.flink.savepoints.enabled }}
    s3.access-key: {{ .Values.flink.savepoints.accessKey | quote }}
    s3.secret-key: {{ .Values.flink.savepoints.secretKey | quote }}
    s3.endpoint: {{ .Values.flink.savepoints.endpoint | quote}}
    s3.path-style-access: "true"
    state.savepoints.dir: "{{ include "cheetah-flink.storageDir" . }}/savepoints"
    state.checkpoints.dir: "{{ include "cheetah-flink.storageDir" . }}/checkpoints"
    state.backend: {{ .Values.flink.state.backend }}
  {{- end }}
  {{- if .Values.monitoring.enabled }}
    {{- range $key, $val := .Values.monitoring.flinkProperties }}
      {{- $key | nindent 4 }}: {{ $val | quote -}}
    {{ end }}
  {{- end }}
  {{- range $key, $val := .Values.flink.flinkProperties }}
    {{ $key }}: {{ $val | quote -}}
  {{ end }}