apiVersion: v1
kind: Service
metadata:
  name: {{ include "cheetah-application.fullname" . }}
  labels:
    {{- include "cheetah-application.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if .Values.monitoring.enabled }}
    - port: {{ .Values.monitoring.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
    {{- end }}
  selector:
    {{- include "cheetah-application.selectorLabels" . | nindent 4 }}
