apiVersion: v2
name: flink-job
description: A Helm chart for handling Cheetah Data Platform Flink jobs

type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.5.1

dependencies:
  - name: image-automation
    condition: image-automation.enabled
    version: "*"
    repository: file://../image-automation
    tags:
      - flux
      - automation
