apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  name: {{ template "cheetah-flink-native.fullname" $ }}
  annotations:
    {{ if .Values.flink.vault.enabled }}
    {{ with .Values.flink.vault }}
    vault.security.banzaicloud.io/vault-tls-secret: {{ .tlsSecret }}
    vault.security.banzaicloud.io/vault-serviceaccount: {{ .serviceaccount }}
    {{ end }}
    {{ end }}
spec:
  image: {{ include "cheetah-flink-native.image" . | quote }}
  imagePullPolicy: {{ .Values.image.pullPolicy }}
  serviceAccount: {{ template "cheetah-flink-native.serviceAccountName" . }}
  flinkVersion: {{ .Values.flink.version | quote }}
  {{- with .Values.restartNonce }}
  restartNonce: {{ . }}
  {{- end }}

  {{- with .Values.flink.job }}
  job:
    jarURI: {{ .jarURI }}
    parallelism: {{ int .parallelism }}
    {{ if .className}}
    entryClass: {{ .className }}
    {{ end }}
    {{- with .args }}
    args:
      {{- range . }}
      - {{ . | quote }}
      {{- end -}}
    {{- end }}
    state: {{ .state }}

    {{- with .savepointTriggerNonce }}
    savepointTriggerNonce: {{ . }}
    {{- end }}
    {{- with .initialSavepointPath }}
    initialSavepointPath: {{ . }}
    {{- end }}
    {{- with .allowNonRestoredState }}
    allowNonRestoredState: {{ . }}
    {{- end }}
    upgradeMode: {{ .upgradeMode | quote }}
  {{- end }}

  {{- with .Values.flink.configuration }}
  flinkConfiguration:
    {{- toYaml . | nindent 4 }}
    {{ if $.Values.monitoring.enabled }}
      {{ with $.Values.monitoring.flinkProperties -}}
        {{ toYaml . | nindent 4 }}
        # {{ range $key, $val := . }}
        #   {{ $key | nindent 4 }}: {{ $val | quote -}}
        # {{ end }}
      {{- end }}
    {{- end }}
  {{- end -}}
  {{ include "cheetah-flink-native.manager" (dict "manager" "jobManager" "value" .Values.flink.jobManager "context" $) | nindent 2 }}
  {{ include "cheetah-flink-native.manager" (dict "manager" "taskManager" "value" .Values.flink.taskManager "context" $) | nindent 2 }}
