apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  name: {{ template "cheetah-flink-native.fullname" $ }}
spec:
  image: {{ include "cheetah-flink-native.image" . | quote }}
  imagePullPolicy: {{ .Values.image.pullPolicy }}
  serviceAccount: {{ template "cheetah-flink-native.serviceAccountName" . }}
  flinkVersion: {{ .Values.flink.version | quote }}

  {{- if .Values.restartNonce }}
  restartNonce: {{ .Values.restartNonce }}
  {{- end }}

  job:
    jarURI: local://{{ .Values.flink.job.jarURI }}
    parallelism: {{ int .Values.flink.job.parallelism }}
    entryClass: {{ .Values.flink.job.className }}
    {{- with .Values.flink.job.args }}
    args:
      {{- range . }}
      - {{ . | quote }}
      {{- end -}}
    {{- end }}
    state: {{ .Values.flink.job.state }}

    {{- if .Values.flink.job.savepointTriggerNonce }}
    savepointTriggerNonce: {{ .Values.flink.job.savepointTriggerNonce }}
    {{- end }}
    {{- if .Values.flink.job.initialSavepointPath }}
    initialSavepointPath: {{ .Values.flink.job.initialSavepointPath }}
    {{- end }}

    {{- if .Values.flink.job.allowNonRestoredState }}
    allowNonRestoredState: {{ .Values.flink.job.allowNonRestoredState }}
    {{- end }}

    upgradeMode: {{ .Values.flink.job.upgradeMode | quote }}

  flinkConfiguration:
    {{- if .Values.flink.savepoints.enabled }}
    s3.endpoint: {{ .Values.flink.savepoints.endpoint | quote }}
    s3.path-style-access: "true"
    state.savepoints.dir: "{{ include "cheetah-flink-native.storageDir" . }}/savepoints"
    state.checkpoints.dir: "{{ include "cheetah-flink-native.storageDir" . }}/checkpoints"
    state.backend: {{ .Values.flink.state.backend | quote }}
    high-availability: org.apache.flink.kubernetes.highavailability.KubernetesHaServicesFactory
    high-availability.storageDir: "{{ include "cheetah-flink-native.storageDir" . }}/ha"
    {{- end }}
    {{- if .Values.monitoring.enabled }}
      {{- range $key, $val := .Values.monitoring.flinkProperties }}
        {{- $key | nindent 4 }}: {{ $val | quote -}}
      {{ end }}
    {{- end }}
    {{- range $key, $val := .Values.flink.flinkProperties }}
      {{- $key | nindent 4 }}: {{ $val | quote -}}
    {{ end }}

  podTemplate:
    apiVersion: v1
    kind: Pod
    metadata:
      name: pod-template
    spec:
    {{- with coalesce .Values.global.imagePullSecrets .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 6 }}
    {{- end }}

  {{ include "cheetah-flink-native.job-manager" (dict "value" .Values.flink.jobManager "context" $ ) | nindent 2 }}

  {{ include "cheetah-flink-native.task-manager" (dict "value" .Values.flink.taskManager "context" $ ) | nindent 2 }}

