apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  name: {{ include "cheetah-flink-native.fullname" $ | trunc 45 }}
  labels:
    {{- include "cheetah-flink-native.labels" . | nindent 4 }}
  annotations:
    {{ if .Values.vault.enabled }}
    {{ with .Values.vault }}
    vault.security.banzaicloud.io/vault-tls-secret: {{ .tlsSecret }}
    vault.security.banzaicloud.io/vault-serviceaccount: {{ .serviceaccount }}
    {{ end }}
    {{ end }}
spec:
  image: {{ include "cheetah-flink-native.image" . | quote }}
  imagePullPolicy: {{ .Values.image.pullPolicy }}
  serviceAccount: {{ include "cheetah-flink-native.serviceAccountName" . }}
  flinkVersion: {{ .Values.flink.version | quote }}
  {{- with .Values.restartNonce }}
  restartNonce: {{ . }}
  {{- end }}

  {{- with .Values.flink.job }}
  job:
    jarURI: {{ .jarURI }}
    parallelism: {{ int .parallelism }}
    {{ with .className}}
    entryClass: {{ . }}
    {{ end }}
    args:
    {{- range $key,$val := $.Values.flink.job.topics }}
      - {{ printf "--%s" $val.name | quote }}
      - {{ printf "%s" $val.value | quote }}
    {{- end }}
    {{- range .args }}
      - {{ . | quote }}
    {{- end }}
    state: {{ .state }}

    {{- with .savepointTriggerNonce }}
    savepointTriggerNonce: {{ . }}
    {{- end }}
    {{- with .initialSavepointPath }}
    initialSavepointPath: {{ . }}
    {{- end }}
    {{- with .allowNonRestoredState }}
    allowNonRestoredState: {{ . }}
    {{- end }}
    upgradeMode: {{ .upgradeMode | quote }}
  {{- end }}

  {{- with .Values.flink.configuration }}
  flinkConfiguration:
    state.savepoints.dir: {{ include "cheetah-flink-native.s3Dir" (dict "context" $ "dir" "savepoints") }}
    state.checkpoints.dir: {{ include "cheetah-flink-native.s3Dir" (dict "context" $ "dir" "checkpoints") }}
    high-availability.storageDir: {{ include "cheetah-flink-native.s3Dir" (dict "context" $ "dir" "ha") }}
    {{- toYaml . | nindent 4 }}
    {{ if $.Values.monitoring.enabled }}
      {{ with $.Values.monitoring.flinkProperties -}}
        {{ toYaml . | nindent 4 }}
      {{- end }}
    {{- end }}
  {{- end -}}
  {{ include "cheetah-flink-native.manager" (dict "manager" "jobManager" "value" .Values.flink.jobManager "context" $) | nindent 2 }}
  {{ include "cheetah-flink-native.manager" (dict "manager" "taskManager" "value" .Values.flink.taskManager "context" $) | nindent 2 }}
