{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/name: flink-kubernetes-operator
    app.kubernetes.io/version: 1.0.1
  name: {{ template "cheetah-flink-native.name" . }}-role
rules:
  - apiGroups:
    - ""
    resources:
    - pods
    - configmaps
    verbs:
    - '*'
  - apiGroups:
    - apps
    resources:
    - deployments
    verbs:
    - '*'
{{- with .Values.rbac.additionalRules }}
  {{- toYaml . | nindent 2 }}
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: flink-kubernetes-operator
    app.kubernetes.io/version: 1.0.1
  name: {{ template "cheetah-flink-native.name" . }}-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "cheetah-flink-native.name" . }}-role
subjects:
- kind: ServiceAccount
  name: {{ template "cheetah-flink-native.serviceAccountName" . }}
{{- end }}