{{- if .Values.ingress.enabled -}}
{{- $fullName := include "cheetah-flink-native.fullname" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: process-tls
  annotations:
    replicator.v1.mittwald.de/replicate-from: flink-operator/flink-jobs-tls
type: kubernetes.io/tls
data:
  tls.key: ""
  tls.crt: ""
{{- end }}
