{{- if .Values.ingress.enabled -}}
{{- if eq .Values.ingress.domain "flink.cheetah.trifork.dev" -}}
{{- $fullName := include "cheetah-flink-native.fullname" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullName }}-process-tls
  annotations:
    replicator.v1.mittwald.de/replicate-from: flink-operator/flink-jobs-tls
type: kubernetes.io/tls
data:
  tls.key: ""
  tls.crt: ""
{{- end }}
{{- end }}
