{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
  {{- include "cheetah-flink-native.labels" . | nindent 4 }}
  name: {{ include "cheetah-flink-native.serviceAccountName" . }}
{{- end }}
