on: [push]

env:
  DEVOPS_DIR: cheetah-charts-test

jobs:
  print-from-script:
    runs-on: ubuntu-latest

    steps:
      - name: Check-out devops repository
        uses: actions/checkout@v2
        with:
          repository: kasttrifork/cheetah-charts-test
          token: ${{ secrets.GITHUB_TOKEN }}
          path: ${{ env.DEVOPS_DIR }}

      - name: Check latest
        run: echo '::set-output name=SELECTED_COLOR::$(python ${{ env.DEVOPS_DIR }}/.github/scripts/test.py --name "first time")'
      - name: Get color
        run: echo "The selected color is ${{ steps.random-color-generator.outputs.SELECTED_COLOR }}"


  jobTet:
    runs-on: ubuntu-latest
    steps:
      - name: set-selected-color
        run: echo '::set-output name=SELECTED_COLOR::green'
        id: random-color-generator
      - name: Get color
        run: echo "The selected color is ${{ steps.random-color-generator.outputs.SELECTED_COLOR }}"
