name: test read yaml action
on: [push, pull_request]
jobs:
  test-yaml-reader:
    runs-on: ubuntu-latest
    name: Test read-yaml
    steps:
      - uses: actions/checkout@v1

      - name: Run read-yaml action
        id: yaml-data
        uses: jbutcher5/read-yaml@1.6     # You may wish to replace main with a version tag such as '1.6' etc.
        with:
          file: './charts/cheetah-application/Chart.yaml'          # File to read from
          key-path: '["version"]' # Access the runs key then the using key and retuns the value.
          env:
            Version: ${{ steps.yaml-data.outputs.data }}
      - name: Display read-yaml output
        run: echo "Version"
