on: [push]

env:
  DEVOPS_DIR: cheetah-charts-test

jobs:
  print-from-script:
    runs-on: ubuntu-latest

    steps:
      - name: Check-out devops repository
        uses: actions/checkout@v2
        with:
          repository: kasttrifork/cheetah-charts-test
          token: ${{ secrets.GITHUB_TOKEN }}
          path: ${{ env.DEVOPS_DIR }}

      - name: Check latest
        id: python
        run: |
          out=$(python ${{ env.DEVOPS_DIR }}/.github/scripts/test.py --name "first time")
          echo '::set-output name=SCRIPT2::$(out)'
          echo $out

  jobTest:
    runs-on: ubuntu-latest
    needs: print-from-script
    steps:
      - name: print variable
        run: echo 'Prints variable out ${{ steps.python.outputs.SCRIPT2 }}'
