name: test read yaml action
on: [push]

env:
  DEVOPS_DIR: cheetah-charts-test

jobs:
  print-from-script:
    name: Hello world
    runs-on: ubuntu-latest
    steps:
    - name: Check-out devops repository
      uses: actions/checkout@v2
      with:
        repository: kasttrifork/cheetah-charts-test
        token: ${{ secrets.GITHUB_TOKEN }}
        path: ${{ env.DEVOPS_DIR }}

    - name: Hello World
      run: python ${{ env.DEVOPS_DIR }}/test.py --name "first time"
      shell: sh

  test-yaml-reader:
    runs-on: ubuntu-latest
    name: Test read-yaml
    steps:
      - uses: actions/checkout@v1

      - name: Run read-yaml action
        id: yaml-data
        uses: jbutcher5/read-yaml@1.6     # You may wish to replace main with a version tag such as '1.6' etc.
        with:
          file: './charts/cheetah-application/Chart.yaml'          # File to read from
          key-path: '["version"]' # Access the runs key then the using key and retuns the value.
      - name: Display read-yaml output
        run: echo "cheetah-application-V${{ steps.yaml-data.outputs.data }}"
