on: [push]

env:
  DEVOPS_DIR: cheetah-charts-test


jobs:
  print-from-script:    
    runs-on: ubuntu-latest
    output:
      output1: ${{ steps.step1.outputs.test}}
    steps:
    - name: Check-out devops repository
      uses: actions/checkout@v2
      with:
        repository: kasttrifork/cheetah-charts-test
        token: ${{ secrets.GITHUB_TOKEN }}
        path: ${{ env.DEVOPS_DIR }}

    - name: Check latest
      run: python ${{ env.DEVOPS_DIR }}/.github/scripts/test.py --name "first time" >> $GITHUB_OUTPUT

  job2:
    runs-on: ubuntu-latest
    needs: print-from-script
    steps:
      - run: echo ${{needs.job1.outputs.output1}}
