name: test read yaml action
on: [push]

env:
  DEVOPS_DIR: cheetah-charts-test

jobs:
  print-from-script:
    output:
      output1: ${{ steps.step1.outputs.test}}
    name: Hello world
    runs-on: ubuntu-latest
    steps:
    - name: Check-out devops repository
      uses: actions/checkout@v2
      with:
        repository: kasttrifork/cheetah-charts-test
        token: ${{ secrets.GITHUB_TOKEN }}
        path: ${{ env.DEVOPS_DIR }}

    - name: Check latest
    - id: step1
      run: python ${{ env.DEVOPS_DIR }}/test.py --name "first time" >> $GITHUB_OUTPUT

  test-yaml-reader:
    runs-on: ubuntu-latest
    outputs:
      output2: ${{ steps.step2.outputs.test }}  
    
    name: Test read-yaml
    steps:
      - uses: actions/checkout@v1

      - name: Run read-yaml action
        id: yaml-data
        uses: jbutcher5/read-yaml@1.6     # You may wish to replace main with a version tag such as '1.6' etc.
        with:
          file: './charts/cheetah-application/Chart.yaml'          # File to read from
          key-path: '["version"]' # Access the runs key then the using key and retuns the value.
      - name: Display read-yaml output
      - id: step2
        run: echo "cheetah-application-V${{ steps.yaml-data.outputs.data }}" >> $GITHUB_OUTPUT
    
    create-release:
      name: Create Release
      runs-on: ubuntu-latest
      needs: print-from-script
      needs: test-yaml-reader
      steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Create Release
          id: create_release
          uses: actions/create-release@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
          with:
            tag_name: ${{ github.ref }}
            release_name: cheetah-application-V${{ steps.yaml-data.outputs.data }}
            body: |
              Changes in this Release
              - First Change
              - Second Change
            draft: false
            prerelease: false