name: automerge

on:
    pull_request:
        branches: [ 'main', 'release/**' ]
        types: [ opened, reopened, labeled, synchronize ]

jobs:
    create-release-branch:
        runs-on: ubuntu-latest
        steps:
          - name: Merge pull requests
            uses: pascalgn/automerge-action@v0.15.6
            env:
                GITHUB_TOKEN: "${{secrets.CHEETAHBOT_READ_PACKAGE}}"
                MERGE_COMMIT_MESSAGE: "automerge"
                MERGE_DELETE_BRANCH: "true"
                MERGE_FILTER_AUTHOR: "cheetahbot"


