name: automerge

on:
    pull_request:
        branches: [ 'main', 'release/**' ]
        types: [ opened, reopened, labeled, synchronize ]

jobs:
    create-release-branch:
        runs-on: ubuntu-latest
        steps:
            - name: Create Pull Request
              uses: peter-evans/enable-pull-request-automerge@v3
              with:
                pull-request-number: ${{ github.event.pull_request.number }}
                merge-method: merge
                token: ${{secrets.CHEETAHBOT_READ_PACKAGE}}
