on: 
    push:
      


env:
  DEVOPS_DIR: cheetah-charts-test
  myBoolean: ${{ 'false' }}
  applicationName: cheetah-application
  brachMain: ${{ 'main' }}

jobs:
  print-from-script:
    runs-on: ubuntu-latest

    steps:

      - name: Check-out devops repository
        uses: actions/checkout@v2
        with:
          repository: kasttrifork/${{ env.DEVOPS_DIR }}
          token: ${{ secrets.GITHUB_TOKEN }}
          path: ${{ env.DEVOPS_DIR }}

      - name: read-yaml 
        id: yaml-data
        uses: jbutcher5/read-yaml@1.6     # You may wish to replace main with a version tag such as '1.6' etc.
        with:
          file: '${{ env.DEVOPS_DIR }}/charts/${{ env.applicationName }}/Chart.yaml'          # File to read from
          key-path: '["version"]' # Access the runs key then the using key and returns the value.  

      - name: read-yaml-output
        run: echo "${{ steps.yaml-data.outputs.data }}"

      - name: Print GitHub event action
        if: ${{ github.ref_name != env.branchMain}}
        run: |
          echo "${{ github.ref_name }}"

      - name: Check latest
        id: python
        run: |
          out=$(python ${{ env.DEVOPS_DIR }}/.github/scripts/test.py --name "${{ env.applicationName }}-V" --version '${{ steps.yaml-data.outputs.data }}' )
          echo "::set-output name=SCRIPT2::${out}"
          echo $out

      - name: print variable
        run: echo 'Prints variable out' ${{ steps.python.outputs.SCRIPT2 }}

        if: ${{ steps.python.outputs.SCRIPT2 == env.myBoolean}}
    
      - name: Checkout code
        uses: actions/checkout@v2
        if: ${{ steps.python.outputs.SCRIPT2 == env.myBoolean}}

      - name: Create Release
        if: ${{ steps.python.outputs.SCRIPT2 == env.myBoolean}}
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ env.applicationName }}-V${{ steps.yaml-data.outputs.data }}
          release_name: ${{ env.applicationName }}-V${{ steps.yaml-data.outputs.data }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false