name: CheckForReleases

on: 
    push:
      branches:
        - "**"
      tags-ignore:
        - "**"

env:
  githubRepo: cheetah-charts-test
      
      
jobs:
  Check-if-a-new-release-or-prerelease-is-required:
    runs-on: ubuntu-latest
    steps:

      - name: Check-out repository
        uses: actions/checkout@v3

      - name: print env
        run: echo '${{ env.githubRepo }}'

      - name: cheetah-application
        uses: ./.github/actions/check-chart
        with: 
          name: cheetah-application
          token: ${{secrets.TOKEN}} # Should be updated to work with bot
          branch: ${{ github.ref_name }}
          repo: ${{ env.githubRepo }}
          









 