on: 
    push:
      




jobs:
  Check-if-a-new-release-or-prerelease-is-required:
    runs-on: ubuntu-latest

    steps:
      - name: Check-out repository
        uses: actions/checkout@v3
      - name: Print a fake token 
        run: echo ${{ secrets.TEST }}
      - name: cheetah-application
        uses: ./.github/actions/check-chart
        with: 
          name: cheetah-application







 