name: Docs publish

on:
  workflow_call:
    inputs:
      chart:
        required: true
        type: string
    secrets:
      token:
        required: true

  workflow_dispatch:
    inputs:
      chart:
        type: choice
        options:
          - cheetah-application
          - flink-job
          - image-automation
          - opensearchrole
          - redpanda-console-oauth2proxy

permissions:
  pull-requests: write
  contents: write
  packages: write

jobs:
  docs:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout the repo
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Read Helm Chart
        id: chart
        uses: jacobtomlinson/gha-read-helm-chart@0.1.3
        with:
          path: ./charts/${{ inputs.chart}}

      - name: Print outputs
        shell: bash
        run: |
          echo "Name - ${{ steps.chart.outputs.name }}"
          echo "Version - ${{ steps.chart.outputs.version }}"

      - name: Update toc file with new version v${{ steps.chart.outputs.version }}
        id: update-toc
        uses: trifork/cheetah-infrastructure-utils-workflows/.github/actions/update-toc@main
        with:
          toc-file: .github/toc.yml
          version: ${{ steps.chart.outputs.version }}
          repo-name: ${{ inputs.chart}}

      - name: create toc-folder/
        if: ${{steps.update-toc.outputs.updated == 'true'}}
        run: |
          mkdir -p toc-folder/
          cp .github/toc.yml toc-folder/

      - name: Deploy toc.yml to GitHub Pages
        if: ${{steps.update-toc.outputs.updated == 'true'}}
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./toc-folder/
          destination_dir: docs/
          commit_message: "Update toc file with new version v${{ env.version }}"
          keep_files: true

      - name: Create Pull Request
        id: cpr
        if: ${{steps.update-toc.outputs.updated == 'true'}}
        uses: peter-evans/create-pull-request@v7.0.8
        with:
          commit-message: "Update toc file with new version v${{ env.version }} for ${{ inputs.chart}}"
          sign-commits: true
          title: "Update toc file with new version v${{ env.version }} for ${{ inputs.chart }}"
          labels: "automated"
          token: ${{ secrets.CHEETAHBOT_WRITE_PACKAGE  || secrets.token}}
          add-paths: .github/toc.yml
          signoff: true
          branch-token: ${{ secrets.GITHUB_TOKEN }}
          branch: Update-toc-file-${{ inputs.chart }}-${{ env.version }}

      - name: Enable Pull Request Automerge
        if: ${{steps.update-toc.outputs.updated == 'true'}}
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          token: ${{ secrets.CHEETAHBOT_WRITE_PACKAGE  || secrets.token}}
          merge-method: squash

      - name: create public/
        run: |
          mkdir -p public/docs/${{ inputs.chart }}/
          cp charts/${{ inputs.chart }}/README.md public/docs/${{ inputs.chart }}
          cp charts/${{ inputs.chart }}/values.yaml public/docs/${{ inputs.chart }}
          cp README.md public/docs

      - name: Add YamlMine to values.yaml
        run: |
          # Add YamlMine to vlalues.yaml
          yaml_mime="### YamlMime:ManagedReference"
          file="public/docs/${{ inputs.chart }}/values.yaml"

          # Check if the file already contains "YamlMime" in the first line
          if ! grep -q "YamlMime" "$file"; then
            sed -i "1s/^/$yaml_mime\n/" "$file"
            echo "Added YamlMime to $file"
          else
            echo "YamlMime already present in $file, skipping."
          fi

      - name: Deploy to GitHub Pages
        id: deployment
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public/docs/${{ inputs.chart }}
          exclude_assets: ""
          destination_dir: docs/${{ inputs.chart }}/v${{ env.version }}
          commit_message: "Deploy docs for version v${{ env.version }}"
          keep_files: true

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          exclude_assets: './public, ./toc-folder'
          commit_message: "Deploy repo to gh pages"
          keep_files: true

      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.CHEETAHBOT_WRITE_PACKAGE  || secrets.token}}
          repository: trifork/cheetah-artifact-documentation
          event-type: docs-update