name: Helm Release Candidate call
on:
  workflow_dispatch:
    inputs:
      helm-chart:
        type: choice
        description: Which hlem chart to create a release candidate for
        default: ""
        options:
          - cheetah-application
          - flink-job
          - opensearchrole
          - redpanda-console-oauth2proxy
jobs:
  verify-flow-and-publish-release-candidate:
    uses: trifork/cheetah-infrastructure-utils-workflows/.github/workflows/helm-create-release-candidate-call.yml@main
    with:
      helm-chart: ${{ inputs.helm-chart}}
    secrets:
      PAT: ${{ secrets.CHEETAHBOT_WRITE_PACKAGE }}
