name: Helm Create Release Call

on:
  workflow_dispatch:
    inputs:
      helm-chart:
        type: choice
        description: Which hlem chart to publish
        default: ""
        options:
          - cheetah-application
          - flink-job
          - opensearchrole
          - cheetah-redpanda-console

jobs:
  lint:
    uses: ./.github/workflows/lint.yaml

  create-release:
    needs: lint
    uses: trifork/cheetah-infrastructure-utils-workflows/.github/workflows/helm-create-release-call.yaml@main
    with:
      helm-chart: ${{ inputs.helm-chart}}
    secrets:
      PAT: ${{ secrets.CHEETAHBOT_WRITE_PACKAGE}}
  
