name: Helm Create Snapshot Call

on:
  workflow_dispatch:
    inputs:
      helm-chart:
        type: choice
        description: Which hlem chart to create a snapshot for
        default: ''
        options:
        - cheetah-application
        - flink-job
        - image-automation

jobs:
  create-snapshot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build and publish snapshot package
        uses: ./.github/actions/helm/helm-publish/
        with:
          package-suffix: "SNAPSHOT${{github.run_number}}"
          PAT: ${{ secrets.GH_TOKEN }}
          chart: ${{inputs.helm-chart}}
