name: Release Helm charts to GCS
# From https://www.arthurkoziel.com/private-helm-repo-with-gcs-and-github-actions/

on:
  push:
    branches:
      - "main"
    paths:
      - "charts/**"
  workflow_dispatch:

env:
  HELM_GCS_VERSION: 0.3.19
  GCS_BUCKET_NAME: "gs://cheetah-helm"
  HELM_REPO: "cheetah-charts"

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.5.2

      - name: Install Helm-GCS plugin
        run: |
          helm plugin install https://github.com/hayorov/helm-gcs \
            --version ${HELM_GCS_VERSION}

      - name: Release to GCS
        env:
          GCLOUD_SERVICE_ACCOUNT_KEY: ${{ secrets.GCLOUD_SERVICE_ACCOUNT_KEY }}
        run: |
          echo "${GCLOUD_SERVICE_ACCOUNT_KEY}" > svc-acc.json
          export GOOGLE_APPLICATION_CREDENTIALS=svc-acc.json

          echo "Initializing helm repo"
          helm gcs init ${GCS_BUCKET_NAME}

          echo "Adding gcs bucket repo ${GCS_BUCKET_NAME}"
          helm repo add ${HELM_REPO} ${GCS_BUCKET_NAME}

          prev_rev=$(git rev-parse HEAD^)
          echo "Identifying changed charts since git rev ${prev_rev}"

          changed_charts=()
          readarray -t changed_charts <<< "$(git diff --find-renames --diff-filter=d --name-only "$prev_rev" -- charts | cut -d '/' -f 2 | uniq)"

          if [[ -n "${changed_charts[*]}" ]]; then
              for chart in "${changed_charts[@]}"; do
                  echo "Updating dependencies for '$chart'..."
                  helm dependency update "charts/$chart"

                  echo "Packaging chart '$chart'..."
                  chart_file=$(helm package "charts/$chart" | awk '{print $NF}')

                  echo "Pushing $chart_file..."
                  helm gcs push "$chart_file" ${HELM_REPO} --force
              done
          else
              echo "No chart changes detected"
          fi
