name: Helm Create Snapshot Call

on:
  workflow_dispatch:
    inputs:
      helm-chart:
        type: choice
        description: Which helm chart to create a snapshot for
        default: ""
        options:
          - cheetah-application
          - flink-job
          - opensearch-task
          - opensearchrole
          - redpanda-console-oauth2proxy

jobs:
  create-snapshot:
    uses: trifork/cheetah-infrastructure-utils-workflows/.github/workflows/helm-create-snapshot-call.yml@main
    with:
      helm-chart: ${{ inputs.helm-chart}}
    secrets:
      PAT: ${{ secrets.CHEETAHBOT_WRITE_PACKAGE }}
