name: Chart linting and testing

on:
  pull_request:
    branches:
      - main
    paths:
      - "charts/**"
  workflow_dispatch:

jobs:
  chart-lint:
    name: Helm chart linting
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Helm
        uses: Azure/setup-helm@v1
        with:
          version: v3.5.2

      # Python is required because `ct lint` runs Yamale (https://github.com/23andMe/Yamale) and
      # yamllint (https://github.com/adrienverge/yamllint) which require Python
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install chart-testing
        uses: helm/chart-testing-action@v2.1.0

      - name: Chart linting
        run: ct lint --config .github/ct-config.yaml
