name: Helm Create Release Branch
on:
  workflow_dispatch:
    inputs:
      helm-chart:
        type: choice
        description: Which hlem chart to increment
        default: ""
        options:
          - cheetah-application
          - flink-job
          - opensearchrole
          - redpanda-console-oauth2proxy

      bump-type:
        type: choice
        description: Increment helm chart main branch
        default: "minor"
        options:
          - major
          - minor

jobs:
  createrelease:
    uses: trifork/cheetah-infrastructure-utils-workflows/.github/workflows/helm-create-release-branch-call.yml@main
    with:
      bump-type: ${{ github.event.inputs.bump-type }}
      helm-chart: ${{ github.event.inputs.helm-chart }}
    secrets:
      PAT: ${{ secrets.CHEETAHBOT_WRITE_PACKAGE}}
