name: Helm Create Release Branch
on:
  workflow_dispatch:
    inputs:
      helm-chart-increment:
        type: choice
        description: Which hlem chart to increment
        default: ''
        options:
        - cheetah-application
        - flink-job
        - image-automation

      main-increment:
        type: choice
        description: Increment helm chart main branch
        default: 'minor'
        options:
        - major
        - minor

jobs:
  create-release-branch-helm:
      uses: trifork/cheetah-infrastructure-utils/.github/workflows/helm-create-release-branch.yml@main
      with:
        helm-chart-increment: ${{ inputs.helm-chart-increment }}
        main-increment: ${{ inputs.main-increment }}
      secrets:
        PAT: ${{ secrets.GH_TOKEN }}
