name: Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0
      - run: |
          out=$(python .github/scripts/test2.py testmig)
          out2="${out//'%'/'%25'}"
          out3="${out//$'\n'/'%0A'}"
          out4="${out//$'\r'/'%0D'}" 
          echo "::set-output name=changelog::$out"
          echo "::set-output name=changelog2::$out2"
          echo "::set-output name=changelog3::$out3"
          echo "::set-output name=changelog4::$out4"
        id: step1
      - name: Print changelog
        run: | 
          echo "${{ steps.step1.outputs.changelog }}"
          echo "${{ steps.step1.outputs.changelog2 }}"
          echo "${{ steps.step1.outputs.changelog3 }}"
          echo "${{ steps.step1.outputs.changelog4 }}"