name: GitHub Actions Demo
run-name: Kasper is testing out GitHub Actions 🚀
on: [push]

env:
  log4: ${{ 'true cheetah-application-v14.621.5-preRelease' }}
  myBoolean_false: ${{ 'false' }}
  myBoolean_true: ${{ 'true' }}
  branchMain: ${{'main'}}


jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a Kasper event."

      - name: checkout
        uses: actions/checkout@v3
        
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - run: |
          pip install pyyaml requests

      - name: run script
        id: python
        run: |
          output=$(python .github/scripts/test2.py --token '${{ secrets.GITHUB_TOKEN }}' --branch '${{ github.ref_name }}')
          out2="${output//'%'/'%25'}"
          out3="${output//$'\n'/'%0A'}"
          out4="${output//$'\r'/'%0D'}" 
          echo "::set-output name=changelog2::$out2"
          echo "::set-output name=changelog3::$out3"
          echo "::set-output name=changelog4::$out4"

      - name: Print Branch
        run: echo '${{github.ref_name}}'

      - name: print variable
        run: |
          echo "${{ steps.python.outputs.changelog4 }} log4"
          echo "${{ steps.python.outputs.changelog3 }} log3"
          echo "${{ steps.python.outputs.changelog3 }} log2"


      - name: Read Chart.yaml and collect version 
        id: cheetah-application-version
        uses: jbutcher5/read-yaml@1.6     # You may wish to replace main with a version tag such as '1.6' etc.
        with:
          file: 'charts/cheetah-application/Chart.yaml'          # File to read from
          key-path: '["version"]' # Access the runs key then the using key and returns the value.  

      - name: read-yaml-output
        run: echo "${{ steps.cheetah-application-version.outputs.data }}"

      - name: Check if a new prerelease for cheetah-application should be created
        if: ${{ steps.python.outputs.changelog4 == env.myBoolean_false &&  github.ref_name == env.branchMain}}
        uses: actions/checkout@v2

      - name: Create preRelease
        if: ${{ steps.python.outputs.changelog4 == env.myBoolean_false &&  github.ref_name == env.branchMain}}
        id: create_Prerelease
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token

        with:
          tag_name: cheetah-application-v${{ steps.cheetah-application-version.outputs.data }}-prerelease-${{ github.ref_name }}
          release_name: cheetah-application-v${{ steps.cheetah-application-version.outputs.data }}-prerelease-${{ github.ref_name }}
          body: |
            Be aware that this a prerelease. This version is not stable
          draft: false
          prerelease: true




      - name: Check if a new release for cheetah-application should be created
        if: ${{ steps.python.outputs.out2 == env.myBoolean_false && github.ref_name == env.branchMain}}
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        
        with:
          tag_name: ${{ env.applicationName }}-V${{ steps.cheetah-application-version.outputs.data }}
          release_name: ${{ env.applicationName }}-V${{ steps.cheetah-application-version.outputs.data }}
          body: |
            This is a stable release
          draft: false
          prerelease: false
